/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rene' at '9/24/16 11:47 PM' with Gradle 3.1
 *
 * @author Rene, @date 9/24/16 11:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
