language: generic # don't install any environment
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "ef2422ab18d4"
  - COMMIT_AUTHOR_EMAIL: "rene@breskeby.com"
