import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Rene' at '9/23/16 10:30 PM' with Gradle 3.0-rc-1
 *
 * @author Rene, @date 9/23/16 10:30 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void canUseMockito() {
        // mock creation
        List mockedList = mock(List.class);

        // using mock object - it does not throw any "unexpected interaction" exception
        mockedList.add("one");
        mockedList.clear();

        // selective, explicit, highly readable verification
        verify(mockedList).add("one");
        verify(mockedList).clear();
    }

    @Ignore
    @Test public void randomIsNotRandomAtAll() {
        assertEquals(new Library().someNotSoRandomString(), "abc");
    }
}
