import org.apache.commons.lang3.RandomStringUtils;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rene' at '9/23/16 10:30 PM' with Gradle 3.0-rc-1
 *
 * @author Rene, @date 9/23/16 10:30 PM
 */
public class Library {
    // some comment
    public boolean someLibraryMethod() {
        RandomStringUtils.randomAlphabetic(10);

        return true;
    }

}
